//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleGameRpg.Engine.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleGameRpg.Engine.Resources.Languages.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Press any key to continue . . . def.
        /// </summary>
        internal static string Intro_PressAnyKey {
            get {
                return ResourceManager.GetString("Intro_PressAnyKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  This console application created as a pet-project by Sergey V. For informational purposes only. .
        /// </summary>
        internal static string MainMenu_Credits {
            get {
                return ResourceManager.GetString("MainMenu_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на    Exit def   .
        /// </summary>
        internal static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to exit? Enter - yes | Esc - no.
        /// </summary>
        internal static string MainMenu_ExitQuestion {
            get {
                return ResourceManager.GetString("MainMenu_ExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на    Settings  def .
        /// </summary>
        internal static string MainMenu_Settings {
            get {
                return ResourceManager.GetString("MainMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  ∙ Start game ∙ def .
        /// </summary>
        internal static string MainMenu_StartGame {
            get {
                return ResourceManager.GetString("MainMenu_StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hint: in order to control menu  use buttons W↑ and S↓.
        /// </summary>
        internal static string MainMenu_Tip1 {
            get {
                return ResourceManager.GetString("MainMenu_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To choose press Enter.
        /// </summary>
        internal static string MainMenu_Tip2 {
            get {
                return ResourceManager.GetString("MainMenu_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sounds: disabled.
        /// </summary>
        internal static string SettingsMenu_Music_Off {
            get {
                return ResourceManager.GetString("SettingsMenu_Music_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sounds: enabled.
        /// </summary>
        internal static string SettingsMenu_Sounds_On {
            get {
                return ResourceManager.GetString("SettingsMenu_Sounds_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  = Language interface = .
        /// </summary>
        internal static string SettingsMenu_UILang {
            get {
                return ResourceManager.GetString("SettingsMenu_UILang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string SettingsMenu_UILang_En {
            get {
                return ResourceManager.GetString("SettingsMenu_UILang_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Russian.
        /// </summary>
        internal static string SettingsMenu_UILang_Ru {
            get {
                return ResourceManager.GetString("SettingsMenu_UILang_Ru", resourceCulture);
            }
        }
    }
}
